# Generated by Django 5.0.6 on 2024-06-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudents',
            name='classroom',
        ),
        migrations.AddField(
            model_name='tblstudents',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='authentication.classroom'),
        ),
        migrations.AddField(
            model_name='tblstudents',
            name='iCap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblstudents',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Eoh1Ch2bSVoCVEiRqpdmT6$ClbNiyGwX0L6DfVq99dManH186EkbrUCMhv6w4Xjj+Q=', max_length=128),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='authentication.tblstudents'),
        ),
        migrations.AlterField(
            model_name='tblstudents',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='authentication.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='authentication.attendancesession'),
        ),
    ]
